name: golden_tests_utils
description: Utils for golden tests
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  glob: ^2.0.2
  golden_toolkit: ^0.11.0
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  - ../google_fonts/
